### ISSUE TITLE
mistake in startRef cause exception and success

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#103]
mistake in startRef, cause exception and success.

```
~/java/git-others/checkstyle/contribution/releasenotes-xdoc-builder/target [master|● 3✖ 1] $ java -jar releasenotes-xdoc-builder-1.0-all.jar -localRepoPath /home/rivanov/java/git-others/checkstyle/checkstyle -startRef 7.0 -releaseNumber 7.1

Generation succeed!
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.lookupCommit(RevWalk.java:676)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:333)
	at org.eclipse.jgit.api.LogCommand.not(LogCommand.java:217)
	at org.eclipse.jgit.api.LogCommand.addRange(LogCommand.java:246)
	at com.github.checkstyle.NotesBuilder.getCommitsBetweenReferences(NotesBuilder.java:151)
	at com.github.checkstyle.NotesBuilder.buildResult(NotesBuilder.java:84)
	at com.github.checkstyle.Main.runNotesBuilder(Main.java:136)
	at com.github.checkstyle.Main.main(Main.java:88)
```

**Comment by romani** [comment]
@Vladlis , as you updating this code, can you take a look at this weird and sad bug.

**Comment by romani** [comment]
kind of the same problem is that is " -generateAll" is not setup it is still "Generation succeed!"  but no files generated at all!
