### ISSUE TITLE
StringIndexOutOfBoundsException on unexpected revert commit format

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#225]
after my revert of commit with custom modification for commit message...... my bad.
```
LATEST_RELEASE_TAG=checkstyle-7.7
CS_RELEASE_VERSION=7.8
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -32
	at java.lang.String.substring(String.java:1954)
	at com.github.checkstyle.NotesBuilder.getIgnoredCommits(NotesBuilder.java:183)
	at com.github.checkstyle.NotesBuilder.buildResult(NotesBuilder.java:85)
	at com.github.checkstyle.Main.runNotesBuilder(Main.java:148)
	at com.github.checkstyle.Main.main(Main.java:94)
```

**Comment by romani** [comment]
workaround/fix is merged
