### ISSUE TITLE
patch-diff-report-tool: NPE in jxr on non-compilable file

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#226]
````
java -jar /contribution/patch-diff-report-tool/target/patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --patchReport /contribution/checkstyle-tester/reports/savepull/apacheapex/checkstyle-result.xml --output /contribution/checkstyle-tester/results/apacheapex --patchConfig /var/www/html/reports/c3d8c8691492f69b47220e1b588b729a --refFiles /contribution/checkstyle-tester/reports/saverefs
patch-diff-report-tool execution started.
XML parsing is started.
Creation of configuration report is started.
Creation of diff html site is started.
Unable to processPath /contribution/checkstyle-tester/reports/saverefs/apacheapex/apex-app-archetype/src/main/resources/archetype-resources/src/test/java/__packageInPathFormat__/ApplicationTest.java => /contribution/checkstyle-tester/results/apacheapex/xref/apacheapex/apex-app-archetype/src/main/resources/archetype-resources/src/test/java/__packageInPathFormat__/ApplicationTest.java.html
Exception in thread "main" java.lang.NullPointerException
    at org.apache.maven.jxr.pacman.JavaFileImpl.parse(JavaFileImpl.java:108)
    at org.apache.maven.jxr.pacman.JavaFileImpl.<init>(JavaFileImpl.java:64)
    at org.apache.maven.jxr.pacman.FileManager.getFile(FileManager.java:68)
    at org.apache.maven.jxr.JavaCodeTransform.appendHeader(JavaCodeTransform.java:294)
    at org.apache.maven.jxr.JavaCodeTransform.transform(JavaCodeTransform.java:376)
    at org.apache.maven.jxr.JavaCodeTransform.transform(JavaCodeTransform.java:443)
    at com.github.checkstyle.site.XrefGenerator.generateXref(XrefGenerator.java:120)
    at com.github.checkstyle.site.SiteGenerator.generateBody(SiteGenerator.java:164)
    at com.github.checkstyle.site.SiteGenerator.generate(SiteGenerator.java:96)
    at com.github.checkstyle.Main.main(Main.java:173)
patch-diff-report-tool failed on apacheapex
````
repo: apacheapex
file: `apex-app-archetype/src/main/resources/archetype-resources/src/test/java/__packageInPathFormat__/ApplicationTest.java`

Snippet of contents of result xml file:
````
<file name="/contribution/checkstyle-tester/reports/saverefs/apacheapex/apex-app-archetype/src/main/resources/archetype-resources/src/test/java/__packageInPathFormat__/ApplicationTest.java">
<error line="0" severity="error" message="Got an exception - com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the analysis of file /contribution/checkstyle-tester/reports/saverefs/apacheapex/apex-app-archetype/src/main/resources/archetype-resources/src/test/java/__packageInPathFormat__/ApplicationTest.java." source="com.puppycrawl.tools.checkstyle.Checker"/>
</file>
````

**Comment by romani** [comment]
Fix is merged
