### ISSUE TITLE
checkstyle-tester: launch.groovy fails on travis

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#263]
from checkstyle/checkstyle#5086

https://travis-ci.org/checkstyle/checkstyle/jobs/273071481#L985

one more problem to new "trusty" ubuntu images, there are only 4G memory on them:
```
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-site-plugin:3.3:site (default-site) @ sample ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17
[INFO] configuring report plugin org.apache.maven.plugins:maven-jxr-plugin:2.5
[WARNING] Report plugin org.apache.maven.plugins:maven-project-info-reports-plugin has an empty version.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.9
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Source Xref" report, file "xref/index.html" already exists for the English version.
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:2.17
[INFO] Generating "Source Xref" report    --- maven-jxr-plugin:2.5
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at launch.executeCmd(launch.groovy:294)
	at launch.executeCmd(launch.groovy:288)
	at launch$executeCmd$10.callCurrent(Unknown Source)
	at launch.runMavenExecution(launch.groovy:219)
	at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:85)
	at launch.generateCheckstyleReport(launch.groovy:64)
	at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
	at launch.run(launch.groovy:10)
```

**Comment by romani** [comment]
fix is merged, Travis is passed.

**Comment by romani** [comment]
wercker is failing in master and all PRs
NoExceptiontest - Apache Struts failed
```
    Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.puppycrawl.tools:checkstyle:jar:8.3-SNAPSHOT in sevntu-maven (http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2)
```

**Comment by romani** [comment]
I put "export MAVEN_OPTS=-Xmx2048m" to travis config, as only travis have this problem.

I did a testing on local, with printing of MAVEN_OPTS from groovy  .... works fine :
```
Testing Checkstyle started
Cloning git repository 'guava' to repositories/guava folder ...
Cloning into 'repositories/guava'...
Cloning git repository 'guava' - completed

Reseting git sources to commit 'v18.0'
MAVEN_OPTS: -Xmx2048m
HEAD is now at 798803f specify release version numbers
guava is synchronized
   [delete] Deleting directory /home/....java
     [copy] Copying 1744 files to /.....guava
Running 'mvn clean' on src/main/java ...
MAVEN_OPTS: -Xmx2048m
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sample 0.0.1-SNAPSHOT

```
