### ISSUE TITLE
patch-diff-report-tool: add files being processed during exceptions

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#268]
Right now all we see is:
````
java -jar /home/ricky/opensource/contribution/patch-diff-report-tool/target/patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --baseReport /home/ricky/regression_reports/savemaster/openjdk9/checkstyle-result.xml --patchReport /home/ricky/regression_reports/savepull/openjdk9/checkstyle-result.xml --output /home/ricky/regression_reports/diff/openjdk9 --baseConfig /var/www/html/reports/1c638a0bd18e5ec21d3d5172a9650e58 --patchConfig /var/www/html/reports/1c638a0bd18e5ec21d3d5172a9650e58 --refFiles /home/ricky/regression_reports/saverefs
patch-diff-report-tool execution started.
XML parsing is started.
Creation of configuration report is started.
Exception in thread "main" javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Invalid byte 1 of 1-byte UTF-8 sequence.
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:599)
    at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
    at com.github.checkstyle.parser.CheckstyleConfigurationsParser.parseModule(CheckstyleConfigurationsParser.java:137)
    at com.github.checkstyle.parser.CheckstyleConfigurationsParser.parseConfiguration(CheckstyleConfigurationsParser.java:115)
    at com.github.checkstyle.parser.CheckstyleConfigurationsParser.parse(CheckstyleConfigurationsParser.java:92)
    at com.github.checkstyle.Main.main(Main.java:177)
````

I mistakenly thought the exception was in the report, but it is actually in the configuration.
We should print which file we are processing when an exception occurs.
This can happen in configurations and in the report.

**Comment by rnveach** [comment]
As for the cause of the exception, once I remove the DTD it went away, so it was a weird issue.
My file:
````
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="haltOnException" value="false"/>

    <module name="TreeWalker">
<module name="VariableDeclarationUsageDistanceCheck"/>
    </module>
</module>
````

**Comment by romani** [comment]
>http://www.puppycrawl.com/dtds/configuration_1_3.dtd

can you use path from sourceforge ?
Is it persistent issue ?
XML parser have options to validate by dTD/schema or not, that might be a reason why two applications works differently

**Comment by rnveach** [comment]
I switched to `http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd` and regression finished just fine.

> Is it persistent issue ?

It was persistent yesterday and I am still getting the exception today.

**Comment by romani** [comment]
I hope you have workaround now

**Comment by rnveach** [comment]
Fix was merged
