### ISSUE TITLE
releasenotes-builder: StringIndexOutOfBoundsException for inaccurate revert commit

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#286]
commit mesage `Revert config: bump pmd plugin to 3.9.0 version`

```
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
LATEST_RELEASE_TAG=checkstyle-8.8
CS_RELEASE_VERSION=8.9
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at com.github.checkstyle.NotesBuilder.buildResult(NotesBuilder.java:93)
	at com.github.checkstyle.Main.runNotesBuilder(Main.java:148)
	at com.github.checkstyle.Main.main(Main.java:94)
```

**Comment by rnveach** [comment]
@romani This was merged, so it is ok to close?
