### ISSUE TITLE
Travis: migrate groovy based build jobs to ppc64le arch

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#573]
issue described at https://github.com/checkstyle/contribution/pull/569#issuecomment-955700289

new problem:
https://app.travis-ci.com/github/checkstyle/contribution/jobs/545935061#L4245
```
Testing Checkstyle started
Caught: java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildLogger
java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildLogger
  at diff.deleteDir(diff.groovy:662)
  at diff$_generateCheckstyleReport_closure4.doCall(diff.groovy:284)
  at diff.generateCheckstyleReport(diff.groovy:264)
  at diff$generateCheckstyleReport$10.callCurrent(Unknown Source)
  at diff.launchCheckstyleReport(diff.groovy:224)
  at diff$launchCheckstyleReport$6.callCurrent(Unknown Source)
  at diff.run(diff.groovy:30)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.BuildLogger
  ... 7 more
```

https://docs.groovy-lang.org/latest/html/api/groovy/util/AntBuilder.html

> Allows Ant tasks to be used with a Groovy builder-style markup. Requires that {{ant.jar}} is on your classpath which will happen automatically if you are using the Groovy distribution but will be up to you to organize if you are embedding Groovy. If you wish to use the optional tasks you will need to add one or more additional jars from the ant distribution to your classpath - see the library dependencies for more details.

this class is deprecated and looks like Groovy bundle missing it in this Arch.
in new Arch
```
$ groovy --version
Groovy Version: 2.4.17 JVM: 1.8.0_292 Vendor: AdoptOpenJDK OS: Linux
```

in AMD64 arch it is:
```
$ groovy --version
Groovy Version: 2.4.5 JVM: 1.8.0_252 Vendor: Private Build OS: Linux
```

**Comment by romani** [comment]
we can try to use Grape dependency manager in groovy to download ant before execution.

**Comment by romani** [comment]
https://mvnrepository.com/artifact/org.apache.ant/ant/1.10.12

**Comment by romani** [comment]
Fix is merged
