### ISSUE TITLE
patch-diff-report-tool throws NullPointerException

### ISSUE THREAD

**Issue by liscju** [checkstyle/contribution#64]
When i run patch-diff-report-tool i get:

```
liscju@liscju-host:~/Checkstyle/contribution/patch-diff-report-tool/target$ java -jar patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar ~/Checkstyle/liscju.github.io/issue2838v2/before/target/ ~/Checkstyle/liscju.github.io/issue2838v2/after/target/ ~/Checkstyle/contribution/checkstyle-tester/src/main/java/ ~/Checkstyle/liscju.github.io/issue2838v2/diff/
Successfull preparation stage.
Exception in thread "main" java.lang.NullPointerException
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at com.github.checkstyle.data.ParsedContent.addRecords(ParsedContent.java:75)
	at com.github.checkstyle.parser.StaxParserProcessor.parseXmlPortion(StaxParserProcessor.java:211)
	at com.github.checkstyle.parser.StaxParserProcessor.parse(StaxParserProcessor.java:134)
	at com.github.checkstyle.Main.executeStages(Main.java:273)
	at com.github.checkstyle.Main.main(Main.java:237)
```

My version of maven: 3.0.5, java: 1.8.0_45, reports which leads to error i put in https://github.com/liscju/patch-diff-report-tool-npe

**Comment by attatrol** [comment]
@liscju,
does this issue still hapen after you updated your repo to this PR: https://github.com/checkstyle/contribution/pull/62?

**Comment by liscju** [comment]
no, after PR is working fine and i must say that it worked significantly faster than previous edition of tool  for generating report ahsm - good job and issue can be closed.

**Comment by romani** [comment]
thanks all for cooperation
