### ISSUE TITLE
releasenotes-builder: no help or usage print by default

### ISSUE THREAD

**Issue by rnveach** [checkstyle/contribution#733]
````
$ java -jar ~/release/contribution/releasenotes-builder/target/releasenotes-builder-1.0-all.jar

Generation ends with 3 errors.

Remote repository path has not been specified!
Start reference has not been specified!
Release number has not been specified!

$ java -jar ~/release/contribution/releasenotes-builder/target/releasenotes-builder-1.0-all.jar /?

Generation ends with 3 errors.

Remote repository path has not been specified!
Start reference has not been specified!
Release number has not been specified!

$ java -jar ~/release/contribution/releasenotes-builder/target/releasenotes-builder-1.0-all.jar --help
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --help
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:561)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:383)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:334)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:540)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:712)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:679)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:660)
        at com.github.checkstyle.CliProcessor.process(CliProcessor.java:117)
        at com.github.checkstyle.Main.main(Main.java:60)
usage:
...
````

We should print help by default.

**Comment by romani** [comment]
Yes

**Comment by romani** [comment]
fix is merged
