### ISSUE TITLE
dtd dfiles on puppycrawl.com are not accessible

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#741]
problems with puppycrawl domain

```
Starting diff report generation ...
Running command: java -jar /root/project/.ci-temp/contribution/patch-diff-report-tool/target/patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --patchReport reports/pull/12392/guava/checkstyle-result.xml
                        --output reports/diff/guava --patchConfig checks-import-order/checks-imports-error-guava.xml
patch-diff-report-tool execution started.
XML parsing is started.
Creation of configuration report is started.
Exception in thread "main" javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,2]
Message: The markup declarations contained or pointed to by the document type declaration must be well-formed.
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at com.github.checkstyle.parser.CheckstyleConfigurationsParser.parseModule(CheckstyleConfigurationsParser.java:147)
	at com.github.checkstyle.parser.CheckstyleConfigurationsParser.parseConfiguration(CheckstyleConfigurationsParser.java:125)
	at com.github.checkstyle.parser.CheckstyleConfigurationsParser.parse(CheckstyleConfigurationsParser.java:104)
	at com.github.checkstyle.Main.main(Main.java:185)
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at diff.executeCmd(diff.groovy:681)
	at diff.executeCmd(diff.groovy:674)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at diff$_generateDiffReport_closure5.doCall(diff.groovy:422)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at diff.generateDiffReport(diff.groovy:405)
	at diff$generateDiffReport$23.callCurrent(Unknown Source)
	at diff.run(diff.groovy:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Exited with code exit status 1
```

already fixed in some files by https://github.com/checkstyle/contribution/commit/6a8a86ca685e1a45359ccaeb890465058026992d

**Comment by rnveach** [comment]
@romani I assume this is complete?

**Comment by romani** [comment]
Yes
