### ISSUE TITLE
diff.groovy fails in host with non English locale 

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#816]
```
✔ ~/java/github/checkstyle/contribution/checkstyle-tester [master|…2⚑ 2] 
$ groovy diff.groovy --localGitRepo ~/java/github/romani/checkstyle   --baseBranch master --patchBranch plan3d/Issue_3132 --config my-config.xml   --listOfProjects projects-to-test-on.properties
...
Caught: java.lang.IllegalStateException: Error: git repository /home/rivanov/java/github/romani/checkstyle has unstaged changes!
java.lang.IllegalStateException: Error: git repository /home/rivanov/java/github/romani/checkstyle has unstaged changes!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at diff.run(diff.groovy:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

problems is that we grep word in english but 
```
✔ ~/java/github/romani/checkstyle [plan3d/Issue_3132 L|✔] 
 $ git status
На ветке plan3d/Issue_3132
нечего коммитить, нет изменений в рабочем каталоге
```

**Comment by nrmancuso** [comment]
Closed via #817
