### ISSUE TITLE
groovy Runtime error while genrating the report 

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/contribution#839]
I was trying to manually generate a report 
this is my command
 ```
D:\contribution\checkstyle-tester> groovy diff.groovy --localGitRepo  D:\checkstyle 
--baseBranch issue-3502 --patchBranch issue-3502-revertlabel --config my_check.xml
 --listOfProjects projects-to-test-on.properties
```
but I got this error when testing started and we want to clone into checkstyle repo 
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 min
[INFO] Finished at: 2024-02-28T02:39:20+02:00
Testing Checkstyle started
   [delete] Deleting directory D:\contribution\checkstyle-tester\src\main\java
Cloning git repository 'checkstyle' to repositories\checkstyle folder ...
Cloning into 'repositories\checkstyle'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3941 bytes of body are still expected
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 4652 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'repositories\checkstyle'...
error: 5107 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'repositories\checkstyle'...
error: 5561 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'repositories\checkstyle'...
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at diff.generateCheckstyleReport(diff.groovy:271)
        at diff$generateCheckstyleReport$11.callCurrent(Unknown Source)
        at diff.launchCheckstyleReport(diff.groovy:232)
        at diff$launchCheckstyleReport$7.callCurrent(Unknown Source)
        at diff.run(diff.groovy:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
this is my [checks.xml](https://gist.github.com/mahfouz72/333a02f446f50710808ab9e8be023e2d) file and this is [properties_to_test on](https://gist.github.com/mahfouz72/2a511cad45b44e01c2ebab9373a9a9e6)

**Comment by nrmancuso** [comment]
@mahfouz72 please add the following details to your issue description:
1. What operating system you're using
2. What version your operating system is
3. java version
4. Groovy version
5. git version

**Comment by rnveach** [comment]
@nrmancuso He added them.

I tried running my own local to confirm there was no issues, but I got the following error:
````
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
````

@mahfouz72 Do you get the same error when you run the following command in the `checkstyle-tester` repo?
`git clone https://github.com/checkstyle/checkstyle.git repositories\checkstyle`

**Comment by rnveach** [comment]
@mahfouz72 Be aware of the other issue I created.

Also I recommend you use `shortFilePaths` since you are on windows.
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#command-line-arguments

**Comment by mahfouz72** [comment]
> Do you get the same error when you run the following command in PS in the `checkstyle-tester` repo?
> `git clone https://github.com/checkstyle/checkstyle.git repositories\checkstyle`

weird but no cloning checkstyle is successful now
```
PS D:\contribution\checkstyle-tester> git clone https://github.com/checkstyle/checkstyle.git repositories\checkstyle
Cloning into 'repositories\checkstyle'...
remote: Enumerating objects: 240424, done.
remote: Counting objects: 100% (25696/25696), done.
remote: Compressing objects: 100% (1185/1185), done.
Receiving objects: 100% (240424/240424), 92.27 MiB | 1.98 MiB/s, done.eused 214728

Resolving deltas: 100% (140280/140280), done.
Updating files: 100% (6632/6632), done.

```
the old error is gone but I encountered a new error in the middle of the running script 
```
[INFO] 15 reports detected for maven-project-info-reports-plugin:2.7: index, plugin-management, distribution-management, dependency-info, scm, mailing-list, issue-tracking, cim, plugins, license, modules, dependency-management, project-team, summary, dependencies
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1
[INFO] 1 report detected for maven-checkstyle-plugin:3.1.1: checkstyle
[INFO] Rendering site with default locale English (en)
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering content with org.apache.maven.skins:maven-default-skin:jar:1.3 skin.
[INFO] Generating "About" report                --- maven-project-info-reports-plugin:2.7:index
[INFO] Generating "Plugin Management" report    --- maven-project-info-reports-plugin:2.7:plugin-management
[INFO] Generating "Distribution Management" report --- maven-project-info-reports-plugin:2.7:distribution-management
[INFO] Generating "Dependency Information" report --- maven-project-info-reports-plugin:2.7:dependency-info
[INFO] Generating "Source Repository" report    --- maven-project-info-reports-plugin:2.7:scm
[INFO] Generating "Mailing Lists" report        --- maven-project-info-reports-plugin:2.7:mailing-list
[INFO] Generating "Issue Tracking" report       --- maven-project-info-reports-plugin:2.7:issue-tracking
[INFO] Generating "Continuous Integration" report --- maven-project-info-reports-plugin:2.7:cim
[INFO] Generating "Project Plugins" report      --- maven-project-info-reports-plugin:2.7:plugins
[INFO] Generating "Project License" report      --- maven-project-info-reports-plugin:2.7:license
[INFO] Generating "Project Team" report         --- maven-project-info-reports-plugin:2.7:project-team
[INFO] Generating "Project Summary" report      --- maven-project-info-reports-plugin:2.7:summary
[INFO] Generating "Dependencies" report         --- maven-project-info-reports-plugin:2.7:dependencies
[INFO] Generating "Checkstyle" report           --- maven-checkstyle-plugin:3.1.1:checkstyle
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000a9a00000, 578813952, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)#
# There is insufficient memory for the Java Runtime Environment to continue.
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at diff.generateCheckstyleReport(diff.groovy:271)
        at diff$generateCheckstyleReport$10.callCurrent(Unknown Source)
        at diff.launchCheckstyleReport(diff.groovy:232)
        at diff$launchCheckstyleReport$6.callCurrent(Unknown Source)
        at diff.run(diff.groovy:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```
I searched for it and I found that the solution would be increasing the heap size used by IDE but I increased it and still got this error. I use IntelliJ

**Comment by mahfouz72** [comment]
@rnveach I have Ubuntu 22 ( I am on a dual-boot machine). do you recommend using it? or this error is unrelated to the OS

**Comment by nrmancuso** [comment]
@mahfouz72 few things here:
1. You can increase the heap size for the JVM as you’ve mentioned, you can see how we do this using environment variables in our bash scripts that run diff.groovy
2. I personally never run anything aside from single test cases from my IDE; it is just one more layer that can cause issues that have to be debugged. Use the terminal.
3. Though my experience with Windows is very limited, I have a lot of experience with both MacOS and Linux, and I can tell you that Linux provides the best experience for most software development activities.

 I would recommend using your Ubuntu install. Note that this will also simplify attempts to recreate executions from CI since nearly all our CI tasks run on Ubuntu images.

**Comment by mahfouz72** [comment]
> It would be helpful to know how you increased it, by how much, and how much memory you have available.

from the IDE settings help -> increase memory size it was 995 I increased it to 1300 

![m](https://github.com/checkstyle/contribution/assets/125591358/0fbd2f34-d2d6-4896-a559-51df0c91abc6)


> I would recommend using your Ubuntu install

okay I will try to set my environment  in Ubuntu ASAP  to see if these errors are gone

**Comment by nrmancuso** [comment]
>okay I will try to set my environment in Ubuntu ASAP to see if these errors are gone

To be clear, your errors may not be "gone", what I am suggesting above will likely make it easier to debug though.

**Comment by nrmancuso** [comment]
Also, fwiw, I do not ever generate reports locally anymore. You are welcome to fork my report generation repo at https://github.com/nrmancuso/checkstyle-diff-report-generator and add some arguments for base branch to the scripts/workflows, it should be pretty simple.

**Comment by mahfouz72** [comment]
@nrmancuso thank you !.  I will try it because I am still strugling for generating report locally even after using ubuntu .this error appears again while cloning  elasticsearch project. but can I use your report generation if I want to use local branch as base branch not the master?
```
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

**Comment by rnveach** [comment]
Are you behind a proxy, vpn, or anything special like those?

**Comment by mahfouz72** [comment]
> Are you behind a proxy, vpn, or anything special like those?

no

 @nrmancuso @rnveach  after following almost all the solutions in stackoverflow. and rerun the script +10 times. I generated a report using 26 project only. the last one `(jdk 17)` is showing the same error when cloning even after I applied all possible solutions. this error is so annoying

**Comment by rnveach** [comment]
How did you initially clone checkstyle?

**Comment by mahfouz72** [comment]
@rnveach in general I just use git clone with command line and never had this problem.
